In [14]:
import pandas as pd
import numpy as np
import csv
def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x)*(1-sigmoid(x))

d=[]
with open('plantTraits.csv','r')as f:
    data = csv.reader(f)
    for row in data:
        d.append(row)
m=np.matrix(d)
input_set=np.array(m[1:,0:6]).astype(np.int64)

labels=np.array(m[1:,6]).astype(np.int64)
labels = labels.reshape(len(labels),1) #to convert labels to vector
np.random.seed(42)
weights = np.random.rand(6,1)
bias = np.random.rand(1)
lr = 0.02 #learning rate

for epoch in range(500):
    inputs = input_set
    XW = np.dot(inputs, weights)+ bias
    z = sigmoid(XW)
    error = z - labels

    dcost = error
    dpred = sigmoid_derivative(z)
    z_del = dcost * dpred
    inputs = input_set.T
    weights = weights - lr*np.dot(inputs, z_del)
    
    for num in z_del:
        bias = bias - lr*num
        
inputs = input_set
XW = np.dot(inputs, weights)+ bias
z = sigmoid(XW)
error = z - labels


dcost = error
dpred = sigmoid_derivative(z)
z_del = dcost * dpred
inputs = input_set.T
weights = weights-lr*np.dot(inputs, z_del)
for num in z_del:
        bias = bias - lr*num
        
single_pt = np.array([5.5,1,1.25,1,25])
result = np.round(sigmoid(np.dot(input_set, weights) + bias),0)


# Python script for confusion matrix creation. 
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
results = confusion_matrix(labels, result) 
print( 'Confusion Matrix :') 
print(results) 
print( 'Accuracy Score :',accuracy_score(labels, result) ) 
print( 'Report : ') 
print( classification_report(labels, result) ) 


Confusion Matrix :
[[97  0  0]
 [17  0  0]
 [22  0  0]]
Accuracy Score : 0.7132352941176471
Report : 
              precision    recall  f1-score   support

           1       0.71      1.00      0.83        97
           2       0.00      0.00      0.00        17
           3       0.00      0.00      0.00        22

    accuracy                           0.71       136
   macro avg       0.24      0.33      0.28       136
weighted avg       0.51      0.71      0.59       136

